public with sharing class AmbiTestClass {
    public AmbiTestClass() {

    }

    public static void testMethod1() {
        System.debug('This is a test method for AmbiTestClass.');
    }


    public static void testMethod2() {
        System.debug('This is another test method for AmbiTestClass.');
    }

    public static void testMethod3() {
        System.debug('This is yet another test method for AmbiTestClass.');
    }
}